### ISSUE TITLE
Docker Layers and Metadata Badges Report HTTP 400 in Production

### ISSUE THREAD

**Issue by lucashalbert** [badgen/badgen.net#443]
The Docker Layers and Metadata Badges report HTTP 400 errors in production on [badgen.net](https://badgen.net), but not in the development environment.

To test the dev environment, simply clone the [https://github.com/badgen/badgen.net.git](https://github.com/badgen/badgen.net.git) repo, build the master branch, and run.

# [Badgen.net/docker](https://badgen.net/docker) environment
![image](https://user-images.githubusercontent.com/10239909/97433939-a688c480-18f4-11eb-9d65-cf9ecfaf4c98.png)

# Dev environment
![image](https://user-images.githubusercontent.com/10239909/97434071-d6d06300-18f4-11eb-96be-c525cbb3a8d9.png)

**Comment by amio** [comment]
Just did a check, it seems fine
- https://badgen.net/docker
- https://flat.badgen.net/docker

**Comment by amio** [comment]
Got a strange error while deploying to sfo region:

![image](https://user-images.githubusercontent.com/215282/97987689-af0e5d00-1e16-11eb-9f18-8dd5956dc244.png)

**Comment by lucashalbert** [comment]
There is no secret required to query Docker layers or metadata, so I doubt that this particular problem would be contributing to the rogue 400 errors being seen in the Northeastern US. It could, however, be indicating a bigger problem in general with vercel.

**Comment by lucashalbert** [comment]
@amio, any idea on how we can fix these 400 errors? I can try to restructure the code to see if that fixes things.

**Comment by amio** [comment]
Couldn't reproduce it locally, but I just deployed an instance in sfo region, would you take a look? @lucashalbert 
https://badgennet-n9jacaosx.vercel.app/docker

**Comment by lucashalbert** [comment]
@amio, the SFO region instance loads correctly. Do you have the IAD1 region direct URL like you have for the SFO region?

**Comment by amio** [comment]
@lucashalbert Here is the iad deployment https://badgennet-o255hrsym.vercel.app

**Comment by amio** [comment]
Got some empty error logs:

![image](https://user-images.githubusercontent.com/215282/102688115-747a4b80-422f-11eb-9c0c-fb3d81328a24.png)

Strange, it seems only happens on __iad region__ with __docker/layers__ or __docker/metadata__ badge

**Comment by lucashalbert** [comment]
Do you think redeploying to the iad region might help, or is this possibly something that Vercel would assist in troubleshooting? It seems more likely to be a problem with their infrastructure in iad than a problem with the app.

**Comment by amio** [comment]
@styfle It looks like something wrong with iad region:

- sfo https://badgennet-n9jacaosx.vercel.app/docker
- iad https://badgennet-o255hrsym.vercel.app/docker

__docker/layers__ and __docker/metadata__ badge are broken only in iad region, for the error log:

```
{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: Client network socket disconnected before secure TLS connection was established","reason":{"errorType":"Error","errorMessage":"Client network socket disconnected before secure TLS connection was established","code":"ECONNRESET","path":null,"host":"www.google-analytics.com","port":443,"stack":["Error: Client network socket disconnected before secure TLS connection was established","    at connResetException (internal/errors.js:609:14)","    at TLSSocket.onConnectEnd (_tls_wrap.js:1547:19)","    at Object.onceWrapper (events.js:420:28)","    at TLSSocket.emit (events.js:326:22)","    at TLSSocket.EventEmitter.emit (domain.js:483:12)","    at endReadableNT (_stream_readable.js:1223:12)","    at processTicksAndRejections (internal/process/task_queues.js:84:21)"]},"promise":{},"stack":["Runtime.UnhandledPromiseRejection: Error: Client network socket disconnected before secure TLS connection was established","    at process.<anonymous> (/var/runtime/index.js:35:15)","    at process.emit (events.js:326:22)","    at process.emit (/var/task/__sourcemap_support.js:587:21)","    at processPromiseRejections (internal/process/promises.js:209:33)","    at processTicksAndRejections (internal/process/task_queues.js:98:32)"]}
```

Could it be some network issue related to upstream connection (https://auth.docker.io or https://registry.hub.docker.com)?

**Comment by styfle** [comment]
@amio That's what it sounds like. Maybe they blocked the Vercel IP in IAD for some reason? The IP address is not static so its strange to see this happening for so long.

**Comment by amio** [comment]
@styfle I've seen same error happens on other badge occasionally:

![image](https://user-images.githubusercontent.com/215282/103970394-22c83f80-51a3-11eb-8d84-182bded03f24.png)

but this badge seems fine while I check:
https://badgen.net/github/license/doocs/technical-books?color=green

same badge from iad region, still fine while I check:
https://badgennet-o255hrsym.vercel.app/github/license/doocs/technical-books?color=green

**Comment by styfle** [comment]
Perhaps the docker or github API is rate limiting if there are more people visiting from the IAD region?

**Comment by amio** [comment]
Fair guess 👍 let me do a check

**Comment by amio** [comment]
According to this https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#rate-limiting
It would be a 403 Error when it hit rate limiting on GitHub

**Comment by styfle** [comment]
I just realized the screenshot for your error says the request was for www.google-analytics.com, not GitHub or Docker.

You could try wrapping that in a try/catch and see if its only GA affected or other upstream APIs too.
