### ISSUE TITLE
Cannot find module './public/.meta/badges.json'

### ISSUE THREAD

**Issue by razonyang** [badgen/badgen.net#655]
Hi, I'm trying to follow the [developing section](https://github.com/badgen/badgen.net?tab=readme-ov-file#developing) to add a live badge, but got the following error, which parts am I missed?

```sh
npm install

npm run dev  

> dev
> next dev

node:internal/modules/cjs/loader:1149
  const err = new Error(message);
              ^

Error: Cannot find module './public/.meta/badges.json'
Require stack:
- C:\Users\razon\Workspaces\badgen\badgen.net\next.config.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1149:15)
    at C:\Users\razon\Workspaces\badgen\badgen.net\node_modules\next\dist\server\require-hook.js:54:36
    at Module._load (node:internal/modules/cjs/loader:990:27)
    at Module.require (node:internal/modules/cjs/loader:1237:19)
    at mod.require (C:\Users\razon\Workspaces\badgen\badgen.net\node_modules\next\dist\server\require-hook.js:64:28)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\razon\Workspaces\badgen\badgen.net\next.config.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\razon\\Workspaces\\badgen\\badgen.net\\next.config.js'
  ]
}

Node.js v21.6.1
```

**Comment by Falke-Design** [comment]
To get it running on Windows I needed to replace

https://github.com/badgen/badgen.net/blob/861a20a29de85382b26b17f5fc911620a4853457/libs/badge-list.ts#L54

with:

```
import { pathToFileURL } from 'url';

...

const mod = await import(pathToFileURL(rel('../api-legacy', id)).href)
```
